### PR TITLE
Test pause

### PR DESCRIPTION
**Pull request by chriscool**
The first commit in this PR fixes issue #19 (Including test_pause()) by adding test_pause().
And the second commit fixes a small bug in sharness.t while at it.

### CODE REVIEW

**Comment by mlafeldt** [comment]
Thanks for the PR.

Please update `API.md` as well by running `make doc`.

Also, please add the documentation of `test_pause` to `README.git` as it was [done in upstream](https://github.com/git/git/blob/9532ead9875b7b92ff2007f9de61af5874e8839a/t/README#L714-L725).

`$SHELL_PATH` seem to [exist for a reason](https://github.com/mlafeldt/sharness/blob/665e154c365762867ce537a7ca6328516ccd5b44/README.git#L328-L329).

**Comment by chriscool** [comment]
Ok, I will update `API.md`.

About the documentation, test_pause is already documented in README.git there: https://github.com/mlafeldt/sharness/blob/master/README.git#L578, so I think you mean README.md.

**Comment by chriscool** [comment]
About `$SHELL_PATH` I know that in Git it should be used in test scripts.
But in Git it is set and exported, while in sharness, sharness.sh neither sets it nor exports it, so it cannot really be used in sharness test scripts right now.

If you mean that the right fix is to make sharness.sh set it and export it, then I can agree with that, but I think it is a bigger fix, though I may have a look at doing that if you think it is really needed and we agree about how to do it.

**Comment by chriscool** [comment]
I have moved the $SHELL_PATH change into its own PR so we discuss it there.

**Comment by chriscool** [comment]
@mlafeldt could you have a look at the following changes:

- The commit with $SHELL_PATH is now in another PR.
- API.md has been regenerated using `make doc`.

Do you really want me to make some changes to README.git? It already has some information about test_pause:
https://github.com/mlafeldt/sharness/blob/master/README.git#L578

**Comment by chriscool** [comment]
This is rebased on top of master and this is using SHELL_PATH instead of SHELL.

**Pull request merged**
