### PR TITLE
fix color support when tput needs ~/.terminfo

### PR DESCRIPTION
**Pull request by richardhansen**
If `tput` needs `~/.terminfo` for the current `$TERM`, then `tput` will succeed before changing `HOME` to `$SHARNESS_TRASH_DIRECTORY` but fail afterward.  Rather than use `tput` after changing `HOME` and `TERM`, save the output of `tput` before changing either variable so that color support is guaranteed to work.

### CODE REVIEW

**Comment by johnkeeping** [comment]
This approach is different from that taken in Git's `test-lib.sh`, which delays all of the color checks until after `$HOME` has been changed.  However, it looks like you were responsible for [commit 102fc80 (test-lib.sh: do tests for color support after changing HOME)](http://git.kernel.org/cgit/git/git.git/commit/?id=102fc80d32094ad6598b17ab9d607516ee8edc4a) in Git, so presumably there is a good reason for doing it differently here.

Is it worth applying a patch similar to this to upstream Git?

**Comment by richardhansen** [comment]
> This approach is different from that taken in Git's `test-lib.sh`, which delays all of the color checks until after `$HOME` has been changed. However, it looks like you were responsible for [commit 102fc80 (test-lib.sh: do tests for color support after changing HOME)](http://git.kernel.org/cgit/git/git.git/commit/?id=102fc80d32094ad6598b17ab9d607516ee8edc4a) in Git, so presumably there is a good reason for doing it differently here.

Yes, a couple of reasons:
  1. I noticed that that change is buggy :)
  2. that approach disables color unnecessarily

> Is it worth applying a patch similar to this to upstream Git?

Yes, I plan on reverting that commit and applying this one upstream.

**Comment by richardhansen** [comment]
> I plan on reverting that commit and applying this one upstream.

http://thread.gmane.org/gmane.comp.version-control.git/271889

Note that I just updated this branch to match the commit I sent upstream.

**Comment by richardhansen** [comment]
Just pushed another re-roll that incorporates feedback from Peff and Junio.

**Comment by chriscool** [comment]
@richardhansen thanks for this! Let's wait a bit in case there is more feedback on the Git mailiing list, otherwise this LGTM!

**Comment by richardhansen** [comment]
Thank you!

**Pull request merged**
