### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by chriscool**
This is to fix issue #31 (Some documentation about contributing to sharness).

### CODE REVIEW

**Comment by mlafeldt** [comment]
Very nice!

Maybe we should link to it from `README.md` as well?

Also it might be worth noting that API functions have to be documented in [TomDoc](https://github.com/mlafeldt/tomdoc.sh).

**Comment by chriscool** [comment]
Ok I will add a link in the README and a some information about TomDoc. Thanks!

**Comment by chriscool** [comment]
Done!

**Comment by mlafeldt** [comment]
Awesome work! Thank you very much, Christian.

**Comment by chriscool** [comment]
@malfeldt thanks!

It's strange it looks like the links at the bottom of the README are not shown.

**Comment by mlafeldt** [comment]
Not sure what you mean?

**Comment by chriscool** [comment]
At the end of https://raw.githubusercontent.com/mlafeldt/sharness/master/README.md there is:

```
[API documentation]: https://github.com/mlafeldt/sharness/blob/master/API.md
[CONTRIBUTING]: https://github.com/mlafeldt/sharness/blob/master/CONTRIBUTING.md
[COPYING]: https://github.com/mlafeldt/sharness/blob/master/COPYING
[Git]: http://git-scm.com/
[prove(1)]: http://linux.die.net/man/1/prove
[README.git]: https://github.com/mlafeldt/sharness/blob/master/README.git
[Sharness cookbook]: https://github.com/mlafeldt/sharness-cookbook
[Test Anything Protocol]: http://testanything.org/
[twitter]: https://twitter.com/mlafeldt
```

but the above isn't shown by GitHub when looking at: 

https://github.com/mlafeldt/sharness/blob/master/README.md

**Comment by mlafeldt** [comment]
Ah, I see. `[CONTRIBUTING]` is just a markdown link which has to be used somewhere in the text above, like all the other links.

**Comment by chriscool** [comment]
Ah, ok. I didn't know this kind of markdown link.
I will add a link using `[CONTRIBUTING]` somewhere in the text.

**Pull request merged**
